server:
  port: 8008
  tomcat:
    accesslog:
      enabled: true

company:
  companies:
  - id: c1
    name: Big Company
  
  - id: c2
    name: Famous Company

  - id: c3
    name: Small Company

  - id: c4
    name: Middle Company

  - id: c5
    name: Micro Company
  
  - id: c6
    name: Unknown Company

  - id: c7
    name: Normal Company

  - id: c8
    name: Poor Company

  relations:
  - parentId: c1
    subordinateId: c4

  - parentId: c1
    subordinateId: c6

  - parentId: c2
    subordinateId: c8

  - parentId: c2
    subordinateId: c5

  - parentId: c7
    subordinateId: c3

product:
  products:
  - id: p1
    name: Normal Product
    companyId: c1
    price: 199.99
    classification: B
  
  - id: p2
    name: Good Product
    companyId: c2
    price: 199.99
    classification: A

  - id: p3
    name: Bad Product
    companyId: c3
    price: 150.00
    classification: F

  - id: p4
    name: New Product
    companyId: c4
    price: 450.00
    classification: B

  - id: p5
    name: Old Product
    companyId: c5
    price: 50.00
    classification: C

  - id: p6
    name: Latest Product
    companyId: c6
    price: 500.00
    classification: A

  - id: p7
    name: Great Product
    companyId: c7
    price: 1000.00
    classification: S
  
  - id: p8
    name: Legacy Product
    companyId: c8
    price: 20.00
    classification: F

  - id: p9
    name: Intelligent Product
    companyId: c1
    price: 1800.00
    classification: S
  
  - id: p10
    name: Useless Product
    companyId: c2
    price: 99.99
    classification: F

  - id: p11
    name: Well known Product
    companyId: c3
    price: 300.00
    classification: B

  - id: p12
    name: Easy Product
    companyId: c4
    price: 250.00
    classification: C

  - id: p13
    name: Half Done Product
    companyId: c5
    price: 99.99
    classification: F

  - id: p14
    name: Super Product
    companyId: c6
    price: 3000.00
    classification: S

  - id: p15
    name: Complex Product
    companyId: c7
    price: 1000.00
    classification: A

  - id: p16
    name: Developing Product
    companyId: c8
    price: 39.99
    classification: F

priority:
  topPrioritizedProducts:
  - p9
  - p14

  blackListedProducts:
  - p3
  - p15
  - p16

  blackListedCompanies:
  - c2

  priorities:
  - rank: 1
    type: COMPANY
    source: c4

  - rank: 2
    type: PRICE
    dir: ASC
    
  - rank: 3
    type: COMPANY
    source: c7

  - rank: 4
    type: COMPANY
    source: c1

  - rank: 5
    type: CLASSIFICATION
    source: DESC