server:
  port: 8008
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:oracle:thin:@qidev.cqvri9lx1hhi.ap-southeast-1.rds.amazonaws.com:1521:qidev
    username: AIDATAUSER
    password: M5#$y90h

mybatis:
  type-aliases-package: com.qima.interview.dao
  mapper-locations:
  - classpath:mapper/*Mapper.xml